name: Deploy to Render

on:
  push:
    branches:
      - dev-sidy-diop   # ou main selon ta branche

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          docker build \
            --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} \
            -t ${{ secrets.DOCKER_USERNAME }}/mcn-museum:latest .
          
          docker push ${{ secrets.DOCKER_USERNAME }}/mcn-museum:latest


      # - name: Deploy to Render
      #   run: |
      #     curl -X POST \
      #       -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
      #       -H "Content-Type: application/json" \
      #       -d '{"clearCache": true}' \
      #       https://api.render.com/deploy/srv-xxxxxxxxx # ton service ID Render
